---
- name: Packages
  ansible.builtin.import_tasks: packages.yml
  tags: packages

- name: User
  ansible.builtin.import_tasks: user.yml
  tags: user

- name: Foodsoft
  ansible.builtin.import_tasks: foodsoft.yml
  tags: foodsoft

- name: Customizations
  ansible.builtin.import_tasks: customizations.yml
  tags: customizations

- name: Database
  ansible.builtin.import_tasks: database.yml
  tags: database

- name: Postinstall
  ansible.builtin.import_tasks: postinstall.yml
  tags: postinstall

- name: Systemd
  ansible.builtin.import_tasks: systemd.yml
  tags: systemd

- name: Cron
  ansible.builtin.import_tasks: cron.yml
  tags: cron

- name: Monitoring
  ansible.builtin.import_tasks: monitoring.yml
  tags: monitoring

- name: Multicoops
  ansible.builtin.include_tasks: multicoops.yml
  loop: "{{ foodsoft_multi_coops_config }}"
  when: foodsoft_config._multi_coop_install is defined and foodsoft_config_multi_coop_install
  args:
    apply:
      tags: multi_coop
