---
- name: "Systemd | copy service files"
  ansible.builtin.template:
    src: "systemd/{{ item.src }}"
    dest: "/etc/systemd/system/{{ item.dest }}"
    mode: "0644"
  loop:
    - { src: foodsoft-web.service.j2, dest: "{{ foodsoft_web_service }}" }
    - { src: foodsoft-web.socket.j2, dest: "{{ foodsoft_web_socket }}" }
    - { src: foodsoft-smtp.service.j2, dest: "{{ foodsoft_smtp_service }}" }
    - { src: foodsoft-resque.service.j2, dest: "{{ foodsoft_resque_service }}" }
  notify:
    - Restart foodsoft-web
    - Restart foodsoft-web-socket
    - Restart foodsoft-smtp
    - Restart foodsoft-resque

- name: "Systemd | create configuration directory"
  ansible.builtin.file:
    path: /etc/foodsoft
    state: directory
    mode: "0755"

- name: "Systemd | copy configuration"
  ansible.builtin.template:
    src: systemd/foodsoft.conf.j2
    dest: "{{ foodsoft_environment_file }}"
    owner: "{{ foodsoft_user }}"
    group: root
    mode: "0640"
  notify:
    - Restart foodsoft-web
    - Restart foodsoft-smtp
    - Restart foodsoft-resque

- name: "Systemd | enable service"
  ansible.builtin.systemd:
    enabled: true
    daemon_reload: true
    state: started
    name: "{{ item }}"
  loop:
    - "{{ foodsoft_web_service }}"
    - "{{ foodsoft_web_socket }}"
    - "{{ foodsoft_smtp_service }}"
    - "{{ foodsoft_resque_service }}"
